### ISSUE TITLE
Failed to read config file at "/app/app-config.yaml", error at .integrations.github[0].apps[0], failed to include "/app/github-integration.yaml", file does not exist

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#21]
## Issue

When we launch backstage using the image `public.ecr.aws/cnoe-io/backstage:v0.0.2`, then we got within the log of the pod the following error
```
Backend failed to start up Error: Failed to read config file at "/app/app-config.yaml", error at .integrations.github[0].apps[0], failed to include "/app/github-integration.yaml", file does not exist
    at readConfigFile (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:882:15)
    at async _FileConfigSource.readConfigData (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:892:22)
    at async Promise.all (index 0)
    at async _MergedConfigSource.readConfigData (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:962:28)
    at async loadConfigReaderLoop (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:1647:36)
Stream closed EOF for backstage/backstage-b6c97667-cm2l2 (backstage)
```

**Remark**: Is it possible to document what you did to build the backstage image, what you configured AND also to add to the idpbuilder the `github-integration.yaml` file ?

**Comment by nabuskey** [comment]
`v0.0.3` is now available. The only difference is the included config file for backstage. 
backstage app is checked in here: https://github.com/cnoe-io/backstage-app. The github integration file is unnecessary for local build imo.

**Comment by nabuskey** [comment]
Closing this since I don't think this issue is relevant anymore
